#!/usr/bin/env bash

rsync -azP --delete "$PWD/public/images/" node@uncannyforest.com:/home/node/uf/public/images/
rsync -azP --delete "$PWD/config/" node@uncannyforest.com:/home/node/uf/config/
rsync -azP --delete "$PWD/setup/panels/" node@uncannyforest.com:/home/node/uf/setup/panels/

# run this from the top-level directory
# e.g. setup/imgpush
